In [12]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from EngbertMicrosaccadeToolbox import microsac_detection

In [13]:
# Set parameters
SAMPLING = 500
MINDUR = 3
VFAC = 5

In [14]:
# Read raw data (ASCII; subject 01, trial 005)
d = pd.read_csv("data/f01.005.dat", sep="\t", header=None, names=["t", "x_l", "y_l", "x_r", "y_r"])
d.head()
d = d.loc[3000:4499]
d.head()

t      x_l      y_l      x_r      y_r
3000  6000.0  0.01188  0.60588 -0.21384  0.41976
3001  6002.0  0.02376  0.61380 -0.20988  0.41580
3002  6004.0  0.02772  0.62172 -0.19800  0.41976
3003  6006.0  0.03564  0.71280 -0.20196  0.41184
3004  6008.0  0.06336  0.64152 -0.20196  0.42372

In [15]:
np.asarray(d.x_r).shape

(1500,)

In [16]:
aa = np.vstack([np.asarray(d.x_r), np.asarray(d.y_r)]).T

In [18]:
bb = microsac_detection.vecvel(aa, sampling=500)

(1500, 2)


In [23]:
np.median(bb, axis=0)

array([ 0.  , -0.33])

In [26]:
bb


array([[ 0.00000000e+00,  0.00000000e+00],
       [ 3.96000000e+00,  0.00000000e+00],
       [ 1.65000000e+00, -4.62592927e-15],
       ...,
       [-1.65000000e+00,  2.64000000e+00],
       [-9.90000000e-01,  5.94000000e+00],
       [ 0.00000000e+00,  0.00000000e+00]])

In [32]:
msd = np.sqrt(np.median((bb-np.median(bb, axis=0))**2, axis=0))

In [33]:
radius = VFAC * msd

In [37]:
test = ((bb/radius)**2).sum(axis=1)
test

array([0.        , 0.2304    , 0.04      , ..., 0.11111111, 0.3744    ,
       0.        ])

In [47]:
np.where(test>1)[0].shape

(41,)

In [34]:
radius

array([8.25, 9.9 ])

In [13]:
w = np.array([[1,2,3], [1,2,3]]).T
w.cumsum(axis=0)

array([[1, 1],
       [3, 3],
       [6, 6]])

In [68]:
aa[0:10]

array([[-0.21384,  0.41976],
       [-0.20988,  0.4158 ],
       [-0.198  ,  0.41976],
       [-0.20196,  0.41184],
       [-0.20196,  0.42372],
       [-0.20196,  0.42372],
       [-0.20196,  0.42372],
       [-0.19008,  0.42372],
       [-0.18612,  0.41976],
       [-0.15444,  0.4158 ]])

In [109]:
def vecvel(x, sampling):
  N, _ = x.shape
  v = np.zeros((N, 2))
  print(v.shape)
  v[2:(N-2),] = SAMPLING/6*(x[4:N,] + x[3:(N-1),] - x[1:(N-3),] - x[0:(N-4),])
  v[1,] = SAMPLING/2*(x[2,] - x[0,])
  v[(N-2),] = SAMPLING/2*(x[N-1,] - x[(N-3),])  
  return v
  

In [110]:
N, _ = aa.shape
aa[4:N-1,].shape
aa[3:N-2,].shape
aa[1:(N-4),].shape
aa[0:(N-5),].shape

(1495, 2)

In [111]:
aa[N-1,1]

-0.02376

In [112]:
aa[4:N-1,]

array([[-0.20196,  0.42372],
       [-0.20196,  0.42372],
       [-0.20196,  0.42372],
       ...,
       [-0.06336, -0.04356],
       [-0.07524, -0.04752],
       [-0.08316, -0.0396 ]])

In [113]:
aa = np.array([[1,2,3,4, 5, 6],[1,2,3,4,5, 6]]).T
aa.shape

(6, 2)